# Generated by Django 2.2.1 on 2019-10-04 18:39

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='create_date',
            field=models.DateTimeField(verbose_name=datetime.datetime(2019, 10, 4, 18, 39, 29, 447490, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_date',
            field=models.DateTimeField(null=True, verbose_name=datetime.datetime(2019, 10, 4, 18, 39, 29, 446922, tzinfo=utc)),
        ),
    ]
