# Generated by Django 2.2.1 on 2019-10-04 23:52

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0002_auto_20191004_1839'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='create_date',
        ),
        migrations.AddField(
            model_name='comment',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 4, 23, 52, 37, 138868, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_date',
            field=models.DateTimeField(null=True, verbose_name=datetime.datetime(2019, 10, 4, 23, 52, 37, 138295, tzinfo=utc)),
        ),
    ]
