# Generated by Django 2.2.1 on 2019-10-04 23:52

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0003_auto_20191004_2352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 4, 23, 52, 52, 267875, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_date',
            field=models.DateTimeField(null=True, verbose_name=datetime.datetime(2019, 10, 4, 23, 52, 52, 267291, tzinfo=utc)),
        ),
    ]
